feat: AS-545 add vue and angular form examples
mohojojo/dap-ds-examples pull request #1
Opened 2024-11-29 15:58 UTC by krondorl

https://jira.idomsoft.hu/browse/AS-545
Angular és Vue példák

2024-12-21 08:15 UTC, mohojojo requested changes

2024-12-21 08:15 UTC, mohojojo commented on src/preact/src/app.tsx
> +                      clearTimeout(timeOutId);
miert nem a useQuery van hasznalva vagy egy sima useEffect, kene egy debounce hook

https://www.bacancytechnology.com/qanda/react/use-debounce-with-usequery-in-react-query

2024-12-21 08:15 UTC, mohojojo commented on src/solid/src/App.tsx
> +import DapDSTextareaSolid from './components/textarea';
miert kellenek a kulon komponensek? mukodik siman a beimportalt ds komponens

2024-12-21 08:15 UTC, mohojojo commented on src/solid/src/App.tsx
> +            <DapDSInputSolid
https://custom-elements-everywhere.com/#solid

```suggestion
            <dap-ds-input
              id="name"
              label="Teljes név"
              name="name"
              feedbackType="negative"
              value={form.name}
              feedback={errors?.name?.toString()}
              on:dds-change={(e: any) => {
                setForm({name: e.detail.value});
                validateRequired('name', 'Add meg a teljes neved!');
              }}
            >
```

2025-01-03 15:10 UTC, krondorl commented on src/solid/src/App.tsx
> +import DapDSTextareaSolid from './components/textarea';
Nem tudtam, hogy így is megy. Több másik úton próbálkoztam. Köszi a jelzést..

2025-01-03 15:10 UTC, krondorl commented on src/solid/src/App.tsx
> +            <DapDSInputSolid
Javítottam.

2025-01-03 16:26 UTC, krondorl commented on src/preact/src/app.tsx
> +                      clearTimeout(timeOutId);
Nem gondoltam rá, de javítottam.

2025-01-06 07:32 UTC, mohojojo approved these changes

2025-01-06 07:32 UTC, merged